// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv8Mvg_vzv0QlM8jI8xmMz48I5-F7V9dU',
    appId: '1:274612486322:web:069d4f5282a298c6e989ab',
    messagingSenderId: '274612486322',
    projectId: 'authentation-final-projek',
    authDomain: 'authentation-final-projek.firebaseapp.com',
    storageBucket: 'authentation-final-projek.firebasestorage.app',
    measurementId: 'G-0VS3WE8YT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-fQzszoNIjeDhxqdaXCPXxa6obtY5qT0',
    appId: '1:274612486322:android:8f9c4e621c66a706e989ab',
    messagingSenderId: '274612486322',
    projectId: 'authentation-final-projek',
    storageBucket: 'authentation-final-projek.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcAnC1rwcbYX0IAFSw_yURnr00030SMOE',
    appId: '1:274612486322:ios:a4cd58be8f2d428ae989ab',
    messagingSenderId: '274612486322',
    projectId: 'authentation-final-projek',
    storageBucket: 'authentation-final-projek.firebasestorage.app',
    iosClientId: '274612486322-62uu0qmkbgk608mr8bhauq9eohda6947.apps.googleusercontent.com',
    iosBundleId: 'com.example.authFinalProyek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcAnC1rwcbYX0IAFSw_yURnr00030SMOE',
    appId: '1:274612486322:ios:a4cd58be8f2d428ae989ab',
    messagingSenderId: '274612486322',
    projectId: 'authentation-final-projek',
    storageBucket: 'authentation-final-projek.firebasestorage.app',
    iosClientId: '274612486322-62uu0qmkbgk608mr8bhauq9eohda6947.apps.googleusercontent.com',
    iosBundleId: 'com.example.authFinalProyek',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBv8Mvg_vzv0QlM8jI8xmMz48I5-F7V9dU',
    appId: '1:274612486322:web:8c9cbe4b876a789ae989ab',
    messagingSenderId: '274612486322',
    projectId: 'authentation-final-projek',
    authDomain: 'authentation-final-projek.firebaseapp.com',
    storageBucket: 'authentation-final-projek.firebasestorage.app',
    measurementId: 'G-2DK9M3JWBB',
  );
}
